"""

"""

import os

# Name of the toll folder
name_tool_folder = "Building_urban_analysis"
# Get Appdata\local folder
local_appdata = os.environ['LOCALAPPDATA']
# Name  and path to the tool folder
name_tool_folder = "Building_urban_analysis"
path_tool = os.path.join(local_appdata, name_tool_folder)
# Path of the different folders in the tool
path_scripts_tool_folder = os.path.join(path_tool, "Scripts")
path_libraries_tool_folder = os.path.join(path_tool, "Libraries")
path_simulation_temp_folder = os.path.join(path_tool, "Simulation_temp")

# Name of the folders generated by the tool
name_gh_components_logs_folder = "gh_components_logs"
name_temporary_files_folder = "temporary_files"
name_radiation_simulation_folder = 'Irradiance and BIPV Simulation'

# todo @Elie delete these one, they should be in the json file now
name_urban_canopy_envelop_hbjson = "urban_canopy_envelop.hbjson"
name_bounding_box_file_hbjson = "bounding_boxes.hbjson"

# Urban Canopy name and exports
name_urban_canopy_export_file = "urban_canopy"
name_urban_canopy_export_file_pkl = name_urban_canopy_export_file + ".pkl"
name_urban_canopy_export_file_json = name_urban_canopy_export_file + ".json"

# name of the files generated by the tool

# Solar Panels
path_pv_tech_dictionary = os.path.join(path_tool, "Libraries", "Solar_panels", "pv_technologies.json")
