"""

"""

import os

# Name of the toll folder
name_tool_folder = "Building_urban_analysis"
# Get Appdata\local folder
local_appdata = os.environ['LOCALAPPDATA']
# Name  and path to the tool folder
name_tool_folder = "Building_urban_analysis"
path_tool = os.path.join(local_appdata, name_tool_folder)
# Path of the different folders in the tool
path_scripts_tool_folder = os.path.join(path_tool, "Scripts")
path_libraries_tool_folder = os.path.join(path_tool, "Libraries")
path_simulation_temp_folder = os.path.join(path_tool, "Simulation_temp")

# Name of the folders generated by the tool
name_gh_components_logs_folder = "gh_components_logs"
name_temporary_files_folder = "temporary_files"
name_ubes_temp_simulation_folder = "BES_temp_simulation"
name_radiation_simulation_folder = 'Irradiance and BIPV Simulation'
name_ubes_simulation_folder = "BES Simulation"

# Urban Canopy name and exports
name_urban_canopy_export_file = "urban_canopy"
name_urban_canopy_export_file_pkl = name_urban_canopy_export_file + ".pkl"
name_urban_canopy_export_file_json = name_urban_canopy_export_file + ".json"

# name of the files generated by the tool

# BIPV simulation
path_folder_bipv_library = os.path.join(path_libraries_tool_folder, "BIPV")
path_folder_default_bipv_parameters = os.path.join(path_folder_bipv_library, "default")
path_folder_user_bipv_parameters = os.path.join(path_folder_bipv_library, "user")
# UBES
name_ubes_epw_file = "uc_epw_ubes.epw"
name_ubes_hbjson_simulation_parameters_file = "uc_ubes_hb_simulation_parameters.json"
