import os
import sys
import shutil
import logging
import argparse
import json
import shapely
from math import sqrt, isnan, log
import matplotlib.pyplot as plt
import numpy as np

import dragonfly
from honeybee.model import Model
from ladybug_geometry.geometry3d import Point3D, Face3D, Vector3D

from libraries_addons.hb_model_addons import *
#from libraries_addons.hb_model_addons import elevation_and_height_from_HB_model, make_LB_face_footprint_from_HB_model
from libraries_addons.lb_face_addons import make_LB_polyface3D_oriented_bounding_box_from_LB_face3D_footprint, \
    LB_face_footprint_to_lB_polyface3D_extruded_footprint
from libraries_addons.hb_rooms_addons import *
#from libraries_addons.hb_rooms_addons import LB_face_footprint_to_elevated_HB_room_envelop
from libraries_addons.context_filter_algorithm.context_filter_first_pass import is_bounding_box_context_using_mvfc_criterion
from libraries_addons.context_filter_algorithm.context_filter_second_pass import is_HB_Face_context_surface_obstructed_for_target_LB_polyface3d
from libraries_addons.function_for_gis_extraction_to_sort import *


from libraries_addons.solar_radiations.add_sensorgrid_hb_model import *
from libraries_addons.solar_radiations.hb_recipe_settings import hb_recipe_settings
from libraries_addons.solar_radiations.annual_irradiance_simulation import hb_ann_irr_sim
from libraries_addons.solar_radiations.annual_cumulative_value import hb_ann_cum_values

from solar_panel.pv_panel_technology import PvPanelTechnology
from solar_panel.pv_panel import PvPanel

from libraries_addons.solar_panels.useful_functions_solar_panel import load_panels_on_sensor_grid, \
    loop_over_the_years_for_solar_panels, beginning_end_of_life_lca_results_in_lists, results_from_lists_to_dict, \
    get_cumul_values, add_elements_of_two_lists, transform_to_linear_function, find_intersection_functions, \
    generate_step_function
from libraries_addons.solar_panels import pv_efficiency_functions
from libraries_addons.solar_panels import pv_efficiency_functions


from building.context_filter.building_shading_context import BuildingShadingContext
from building.context_filter.building_lwr_context import BuildingLWRContext


